# WIP!!! THIS CURRENTLY EXISTS ON GITHUB JUST FOR MY INDIVIDUAL PROGRESS DEMONSTRATION.

# THIS WAS MY FIRST ATTEMPT AT THE WEB SCRAPER FOR AD ASTRA THAT I MADE DURING MY RESEARCH. YES, IT'S REALLY THAT SMALL.
# IF YOU WANT TO TRY IT FOR YOURSELF, REPLACE THE FILE PATH WITH YOUR OWN VERSION OF ADASTRA'S HTML; NO WAY I'M UPLOADING THAT TO GITHUB.
# ALTHOUGH THE LOGIC IS SOLID, THIS SCRAPER DOES NOT WORK YET BECAUSE HTML OBTAINED DIRECTLY FROM THE SITE CANNOT CONTAIN ALL OF THE CLASSROOM DATA; 
# ADASTRA LOADS IN THE DATA WITH JAVASCRIPT DYNAMICALLY DEPENDING ON THE POSITION OF THE SCROLL BAR.

# ALSO I'LL MAKE THE VARIABLE NAMES MORE PROFESSIONAL AND ADD MORE DOCUMENTATION IN THE NEXT VERISONS. :)

from bs4 import BeautifulSoup

soup = BeautifulSoup(open("C:\\Users\\Ethan\\Downloads\\pain.html"), "html.parser")

the_list = soup.select("#tableview-1040 tbody tr .x-grid-cell-first div")

for item in the_list:
    the_data = item.text.strip()
    print(the_data)